substitutions:
  friendly_name: Zehnder ComfoAir Q350
  device_name: comfoair
  device_description: Ventilation system
  filter_time: 5s
  filter_send_every: "1"
  filter_window_size: "3"

packages:
  binary_sensors: !include binary_sensors.yml
  board: !include board.yml
  button: !include button.yml
  canbus: !include canbus.yml
  climate: !include climate.yml
  common: !include common.yml
  fan: !include fan.yml
  select: !include select.yml
  sensors: !include sensors.yml
  switch: !include switch.yml
  text_sensors: !include text_sensors.yml

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-zehnder-comfoair
    version: "2024.8.0"

logger:
  level: INFO
  logs:
    canbus: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_rrm: true
  enable_btm: true
  use_address: 192.168.2.30
  manual_ip:
    static_ip: 192.168.2.30
    gateway: 192.168.2.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password

captive_portal:
improv_serial:

web_server:
  port: 80
  ota: false
  local: true

# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids:
    [
      16,
      49,
      54,
      55,
      65,
      66,
      67,
      81,
      82,
      117,
      118,
      119,
      120,
      121,
      122,
      128,
      129,
      130,
      192,
      209,
      210,
      211,
      212,
      212,
      213,
      214,
      215,
      216,
      217,
      218,
      220,
      221,
      225,
      227,
      274,
      275,
      276,
      277,
      278,
      290,
      291,
      292,
      293,
      294,
    ]
